### PR TITLE
feat: Use unique tab titles for files with same names

### PR DESCRIPTION
**Pull request by MikeAndrson**
Displays unique tab titles for files with same names under different folders, using [UniqueNameBuilder.java](https://github.com/JetBrains/intellij-community/blob/master/platform/util/base/src/com/intellij/filename/UniqueNameBuilder.java) from IntelliJ. (which, FWIW, has tests [here](https://github.com/JetBrains/intellij-community/blob/master/platform/platform-tests/testSrc/com/intellij/openapi/fileEditor/UniqueNameBuilderTest.java), I can add them as well if you want.)

Preview             |  File structure
:-------------------------:|:-------------------------:
  |

### CODE REVIEW

**Comment by MikeAndrson** [comment]
Toggle to disable it:

**Comment by Zeyrox1090** [comment]
:blush-1:

**Comment by Rohit24923** [comment]
IMG-20220314-WA0000


Build version: 0.2.8.2 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-03-14 05:00:06 
Device: Xiaomi Redmi Note 8 
 
Stack trace:  
java.lang.IllegalStateException: Fragment EditorContainerFragment{f228c50} (6e4f68bf-2d7d-464a-927a-719cbdd80367) not associated with a fragment manager.
	at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:1059)
	at com.tyron.code.ui.editor.EditorContainerFragment$2.lambda$onTabSelected$0$com-tyron-code-ui-editor-EditorContainerFragment$2(EditorContainerFragment.java:142)
	at com.tyron.code.ui.editor.EditorContainerFragment$2$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8037)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

User actions: 
2022-03-14 04:54:56: MainActivity created
2022-03-14 04:54:56: MainActivity resumed
2022-03-14 04:55:52: MainActivity paused
2022-03-14 04:55:52: SettingsActivity created
2022-03-14 04:55:52: SettingsActivity resumed
2022-03-14 04:56:01: SettingsActivity paused
2022-03-14 04:56:02: SettingsActivity resumed
2022-03-14 04:56:05: SettingsActivity paused
2022-03-14 04:56:05: MainActivity resumed
2022-03-14 04:56:06: SettingsActivity destroyed
2022-03-14 04:56:35: MainActivity paused
2022-03-14 04:56:35: SettingsActivity created
2022-03-14 04:56:35: SettingsActivity resumed
2022-03-14 04:56:49: SettingsActivity paused
2022-03-14 04:56:49: MainActivity resumed
2022-03-14 04:56:50: SettingsActivity destroyed
2022-03-14 04:57:14: MainActivity paused
2022-03-14 04:57:14: SettingsActivity created
2022-03-14 04:57:14: SettingsActivity resumed
2022-03-14 04:57:22: SettingsActivity paused
2022-03-14 04:57:22: MainActivity resumed
2022-03-14 04:57:23: SettingsActivity destroyed
2022-03-14 04:57:29: MainActivity paused
2022-03-14 04:57:29: SettingsActivity created
2022-03-14 04:57:29: SettingsActivity resumed
2022-03-14 04:57:32: MainActivity destroyed
2022-03-14 04:57:32: MainActivity created
2022-03-14 04:57:32: MainActivity resumed
2022-03-14 04:57:32: MainActivity paused
2022-03-14 04:57:32: SettingsActivity paused
2022-03-14 04:57:32: SettingsActivity destroyed
2022-03-14 04:57:32: SettingsActivity created
2022-03-14 04:57:32: SettingsActivity resumed
2022-03-14 04:57:43: SettingsActivity paused
2022-03-14 04:57:43: MainActivity resumed
2022-03-14 04:57:44: SettingsActivity destroyed
2022-03-14 04:57:48: MainActivity paused
2022-03-14 04:57:49: MainActivity destroyed
2022-03-14 04:58:33: MainActivity created
2022-03-14 04:58:33: MainActivity resumed
2022-03-14 04:59:36: MainActivity paused
2022-03-14 04:59:36: SettingsActivity created
2022-03-14 04:59:36: SettingsActivity resumed

**Comment by MikeAndrson** [comment]
> Build version: 0.2.8.2 ALPHA Build date: 1981-01-01 01:01:02 Current date: 2022-03-14 05:00:06 Device: Xiaomi Redmi Note 8
> 
> Stack trace: java.lang.IllegalStateException: Fragment EditorContainerFragment{f228c50} (6e4f68bf-2d7d-464a-927a-719cbdd80367) not associated with a fragment manager. at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:1059) 

@Rohit24923 I think it's fixed now, can you try again?

**Comment by tyron12233** [comment]
i think the better fix is to unregister the shared preference listener when the fragment's view has been destroyed

**Comment by MikeAndrson** [comment]
> i think the better fix is to unregister the shared preference listener when the fragment's view has been destroyed

Done

**Comment by Rohit24923** [comment]
https://drive.google.com/file/d/1LGgR-LHP15FJXbBpy3Ag3iubirr5nCw-/view?usp=drivesdk
Issue

**Comment by MikeAndrson** [comment]
> https://drive.google.com/file/d/1LGgR-LHP15FJXbBpy3Ag3iubirr5nCw-/view?usp=drivesdk Issue

@Rohit24923 I can't access the link, can you change the privacy setting of that file to "Anyone with the link"?

**Comment by Rohit24923** [comment]
> > https://drive.google.com/file/d/1LGgR-LHP15FJXbBpy3Ag3iubirr5nCw-/view?usp=drivesdk Issue
> 
> @Rohit24923 I can't access the link, can you change the privacy setting of that file to "Anyone with the link"?

Try again

**Comment by MikeAndrson** [comment]
> > > https://drive.google.com/file/d/1LGgR-LHP15FJXbBpy3Ag3iubirr5nCw-/view?usp=drivesdk Issue
> > 
> > 
> > @Rohit24923 I can't access the link, can you change the privacy setting of that file to "Anyone with the link"?
> 
> Try again to watch video

Alright. What seems to be the issue? The behavior is the same as IntelliJ/Android Studio. When there are multiple opened files with the same name thus causing ambiguity, the name of their parent dirs will be shown to make a unique title. If there is no ambiguity, only the file name is shown.

**Comment by Rohit24923** [comment]
@MikeAndrson I requested you to add install function in CodeAssist. For example: When /storage/emulated/0/Details/Code Assist/Cool Hint/app/build/bin/signed.apk clicked on CodeAssist app not shows install option in CodeAssist. Please add this install function

**Pull request merged**
