### PR TITLE
feat: Add View Binding

### PR DESCRIPTION
**Pull request by omeraydindev**
This PR ports/cherry-picks View Binding feature to CodeAssist from the official [data-binding library](https://cs.android.com/androidx/platform/frameworks/data-binding).
(Data Binding logic isn't ported for now, but it can be in the future.)

------------------------

### Steps to enable it in your project:

1- Set `viewBindingEnabled` to `true` in your app module's `app_config.json`.

2- Add the [ViewBinding runtime](https://mvnrepository.com/artifact/androidx.databinding/viewbinding) to your project using Library Manager. Then `Refresh module`.
  (e.g groupId: `androidx.databinding` , artifactId: `viewbinding` , versionName: `7.1.2` )

3- ????

4- Profit!!!

------------------------

### TO-DO
- [ ] Write tests for `GenerateViewBindingTask` and maybe `InjectViewBindingTask`
- [ ] Fix Kotlin auto-complete not recognizing binding classes.

------------------------

### CODE REVIEW

**Comment by chengzhuangjie** [comment]
Please support as soon as possible

**Comment by MoonKnight18** [comment]
Build version: 0.2.8.2 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-03-19 15:21:16 
Device: Xiaomi Redmi 8 
 
Stack trace:  
java.lang.IllegalArgumentException: Parameter 'file' is not a file: /storage/emulated/0/Code Assist/nzjz/app/src/main/java/com/snj/ActivityMainBinding.java
	at org.apache.commons.io.FileUtils.requireFile(FileUtils.java:2737)
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:2446)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:3540)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:3524)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorFragment.lambda$save$11$com-tyron-code-ui-editor-impl-text-rosemoe-CodeEditorFragment(CodeEditorFragment.java:550)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorFragment$$ExternalSyntheticLambda1.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

User actions: 
2022-03-19 15:18:17: MainActivity created
2022-03-19 15:18:18: MainActivity resumed
2022-03-19 15:18:18: MainActivity paused
2022-03-19 15:18:19: MainActivity resumed
2022-03-19 15:18:38: MainActivity paused
2022-03-19 15:18:38: SettingsActivity created
2022-03-19 15:18:39: SettingsActivity resumed
2022-03-19 15:18:49: SettingsActivity paused
2022-03-19 15:18:49: MainActivity resumed
2022-03-19 15:18:50: SettingsActivity destroyed
2022-03-19 15:19:08: MainActivity paused
2022-03-19 15:19:34: MainActivity resumed
2022-03-19 15:20:22: MainActivity paused
2022-03-19 15:20:24: MainActivity resumed

**Comment by ErrorFoundF** [comment]
Build version: 0.2.8.2 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-03-19 15:21:16 
Device: Xiaomi Redmi 8 
 
Stack trace:  
java.lang.IllegalArgumentException: Parameter 'file' is not a file: /storage/emulated/0/Code Assist/nzjz/app/src/main/java/com/snj/ActivityMainBinding.java
	at org.apache.commons.io.FileUtils.requireFile(FileUtils.java:2737)
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:2446)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:3540)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:3524)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorFragment.lambda$save$11$com-tyron-code-ui-editor-impl-text-rosemoe-CodeEditorFragment(CodeEditorFragment.java:550)
	at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorFragment$$ExternalSyntheticLambda1.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

User actions: 
2022-03-19 15:18:17: MainActivity created
2022-03-19 15:18:18: MainActivity resumed
2022-03-19 15:18:18: MainActivity paused
2022-03-19 15:18:19: MainActivity resumed
2022-03-19 15:18:38: MainActivity paused
2022-03-19 15:18:38: SettingsActivity created
2022-03-19 15:18:39: SettingsActivity resumed
2022-03-19 15:18:49: SettingsActivity paused
2022-03-19 15:18:49: MainActivity resumed
2022-03-19 15:18:50: SettingsActivity destroyed
2022-03-19 15:19:08: MainActivity paused
2022-03-19 15:19:34: MainActivity resumed
2022-03-19 15:20:22: MainActivity paused
2022-03-19 15:20:24: MainActivity resumed

**Comment by MikeAndrson** [comment]
> Build version: 0.2.8.2 ALPHA Build date: 1981-01-01 01:01:02 Current date: 2022-03-19 15:21:16 Device: Xiaomi Redmi 8
> 
> Stack trace: java.lang.IllegalArgumentException: Parameter 'file' is not a file: /storage/emulated/0/Code Assist/nzjz/app/src/main/java/com/snj/ActivityMainBinding.java at org.apache.commons.io.FileUtils.requireFile(FileUtils.java:2737) at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:2446) at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:3540) at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:3524) at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorFragment.lambda$save$11$com-tyron-code-ui-editor-impl-text-rosemoe-CodeEditorFragment(CodeEditorFragment.java:550) at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorFragment$$ExternalSyntheticLambda1.run(Unknown Source:2) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:919)
> 
> User actions: 2022-03-19 15:18:17: MainActivity created 2022-03-19 15:18:18: MainActivity resumed 2022-03-19 15:18:18: MainActivity paused 2022-03-19 15:18:19: MainActivity resumed 2022-03-19 15:18:38: MainActivity paused 2022-03-19 15:18:38: SettingsActivity created 2022-03-19 15:18:39: SettingsActivity resumed 2022-03-19 15:18:49: SettingsActivity paused 2022-03-19 15:18:49: MainActivity resumed 2022-03-19 15:18:50: SettingsActivity destroyed 2022-03-19 15:19:08: MainActivity paused 2022-03-19 15:19:34: MainActivity resumed 2022-03-19 15:20:22: MainActivity paused 2022-03-19 15:20:24: MainActivity resumed

Any particular steps to reproduce the error? Or a screen recording. Either is fine.

**Comment by ErrorFoundF** [comment]
> > Build version: 0.2.8.2 ALPHA Build date: 1981-01-01 01:01:02 Current date: 2022-03-19 15:21:16 Device: Xiaomi Redmi 8
> > Stack trace: java.lang.IllegalArgumentException: Parameter 'file' is not a file: /storage/emulated/0/Code Assist/nzjz/app/src/main/java/com/snj/ActivityMainBinding.java at org.apache.commons.io.FileUtils.requireFile(FileUtils.java:2737) at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:2446) at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:3540) at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:3524) at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorFragment.lambda$save$11$com-tyron-code-ui-editor-impl-text-rosemoe-CodeEditorFragment(CodeEditorFragment.java:550) at com.tyron.code.ui.editor.impl.text.rosemoe.CodeEditorFragment$$ExternalSyntheticLambda1.run(Unknown Source:2) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:919)
> > User actions: 2022-03-19 15:18:17: MainActivity created 2022-03-19 15:18:18: MainActivity resumed 2022-03-19 15:18:18: MainActivity paused 2022-03-19 15:18:19: MainActivity resumed 2022-03-19 15:18:38: MainActivity paused 2022-03-19 15:18:38: SettingsActivity created 2022-03-19 15:18:39: SettingsActivity resumed 2022-03-19 15:18:49: SettingsActivity paused 2022-03-19 15:18:49: MainActivity resumed 2022-03-19 15:18:50: SettingsActivity destroyed 2022-03-19 15:19:08: MainActivity paused 2022-03-19 15:19:34: MainActivity resumed 2022-03-19 15:20:22: MainActivity paused 2022-03-19 15:20:24: MainActivity resumed
> 
> Any particular steps to reproduce the error? Or a screen recording. Either is fine.

I don't know error because this error show by accident.

**Comment by MikeAndrson** [comment]
Added a basic [test](https://github.com/MikeAndrson/CodeAssist/blob/viewbinding/build-tools/build-tests/src/test/kotlin/com/tyron/builder/compiler/viewbinding/GenerateViewBindingTaskTest.kt) for [GenerateViewBindingTask](https://github.com/MikeAndrson/CodeAssist/blob/viewbinding/build-tools/build-logic/src/main/java/com/tyron/builder/compiler/viewbinding/GenerateViewBindingTask.kt). (As there already extensive tests in the library itself [here](https://github.com/MikeAndrson/CodeAssist/blob/viewbinding/build-tools/viewbinding-lib/src/test/kotlin/com/tyron/viewbinding/tool/writer/ViewBinderGenerateJavaTest.kt)) The PR should now be ready

**Comment by Mdshorifmolla** [comment]
Nice app

**Comment by Johnismaiel** [comment]
Apk

**Review by Johnismaiel — APPROVED** [review]
That's good

**Review by Johnismaiel — CHANGES_REQUESTED** [review]
- - - [ ] great

**Comment by Diogoeae** [comment]
Normalmente quando eu tento passar arquivos AndroidManifest e possuem erros, eu caiu na tela de projeto brinkado/quebrado, nesses casos normalmente ele perde a permissão de acessar o diretório pai temporariamente, chega ser engraçado, mas o projeto vai de F
Desculpe o comentário longo.

**Pull request merged**
