### PR TITLE
feat: minor visual improvements in Layout Editor and project's TreeView

### PR DESCRIPTION
**Pull request by Raival-e**
- show folders first in TreeView.
Screenshot_1640777640

- some improvements in ViewPalette items and new widgets has been added.
Screenshot_1640777678

- some improvements in Attributes Editor.
Screenshot_1640777693

Screenshot_1640777908

### CODE REVIEW

**Comment by tyron12233** [comment]
Thanks! Can you build a debug APK on GitHub Actions from your fork so I can test it out?

**Comment by Zeyrox1090** [comment]
i wanna test it out too

**Comment by Zeyrox1090** [comment]
this is sooo epic

**Comment by Raival-e** [comment]
> Thanks! Can you build a debug APK on GitHub Actions from your fork so I can test it out?

done.

**Comment by Zeyrox1090** [comment]
pog

**Pull request merged**
