### PR TITLE
enhancement peningkatan

### PR DESCRIPTION
**Pull request by AndiHasan97**
please add these features: layout preview, auto completion for kotlin, run in console, menu bar symbol above keyboard, can use google keyboard

### CODE REVIEW

**Comment by leapofazzam123** [comment]
holy fuck

**Comment by AndiHasan97** [comment]
What ? I'm beginner to learn GitHub, sorry if I'm make mistake

Pada tanggal Rab, 25 Mei 2022 08.10, Leap of Azzam ***@***.***>
menulis:

**Comment by Iyxan23** [comment]
You're supposed to create a discussion to suggest an idea. Pull requests are meant for code contributions.

**Comment by AndiHasan97** [comment]
where I can create discussion?

Pada tanggal Rab, 25 Mei 2022 11.25, Iyxan23 ***@***.***>
menulis:

**Pull request closed without merging**
