### PR TITLE
Git Module

### PR DESCRIPTION
**Pull request by PriNova**
This is the integration of the JGit module.

It has a own folder in the codebase.

### CODE REVIEW

**Review by tyron12233 — CHANGES_REQUESTED** [review]
This is a memory leak, the lambda will have an implicit reference to the enclosing class which is the MainFragment class and is then saved to a static kotlin property. 

I suggest using the `EventManager` APIs and subclass the `Event` class to keep the fragments decoupled. See the EventManager [class](https://github.com/tyron12233/CodeAssist/blob/main/app/src/main/java/com/tyron/code/event/EventManager.java) for more information.

To get a global instance of the EventManager, use `ApplicationLoader#getEventManager()`

You can also pass in the `LifecycleOwner` of the fragment's view in the subscribeEvent method to automatically unregister the observer when the fragment has been destroyed.

**Comment by PriNova** [comment]
Thank you for your suggestions and review.
I will have a look about this issue and will commit changes asap

**Comment by PriNova** [comment]
I fixed the leak with the help of LeakCanary 2.8.1 and it gave no leaks anymore.

I chose lambdas in kotlin to avoid interfaces and to avoid extra object overhead .

If, in the future, the git module need more communication with other modules, then switching to the event API will be more powerfull, despite using kotlin solves alot what java lags.

**Comment by PriNova** [comment]
BTW: For events, you can use Kotlinx coroutines BroadcastChannel's & Flow's and make them LiveCycle-& LiveData aware with a viewModelScope as a coroutinecontext.
So an Event API would be obsolete.

**Comment by PriNova** [comment]
Integrated ViewModel for configuration change.
Added Snackbar to notify user-actions
And refactored other logic into module

**Comment by Kryslynn23** [comment]
> module

**Review by Kryslynn23 — APPROVED** [review]
Approve

**Comment by PriNova** [comment]
Thank you for approving this PR @Kryslynn23 .

There were so many changes in nearly 1 year since opening the PR, that there are a lot breaking changes which needs to be resolved first.

I will have a look, if I can manage the time to resolve it and update this PR to the upstream.
Suggestions?

**Comment by PriNova** [comment]
I close this PR because the project seems not to be maintained anymore.

**Pull request closed without merging**
